let start=datetime("2019-12-02T00:00:00.000Z");
let end=datetime("2019-12-03T00:00:00.000Z");
requests
| where timestamp > start and timestamp < end
// this example takes in account the POST requests only, but you can easily adjust the below command for your needs
| where substring(operation_Name, 0, strlen("POST")) == "POST"
| summarize RequestsCount=sum(itemCount), AverageDuration=avg(duration), percentiles(duration, 50, 95, 99) by operation_Name
| order by RequestsCount desc